#!/usr/bin/env perl
use strict;
use warnings;
use FindBin qw< $Bin $Script >;
use lib map { "$Bin/$_" } qw(lib inc/lib/perl5);

use Getopt::Long::Descriptive;
use App::Dwindling;

my ($opt, $usage) = describe_options(
    "$Script %o ::: <stage1> <fwd.fastq> <rev.fastq> [orphans.fastq] [::: <stage2> ... [::: <stage3> ...]]",
    [],
    [ 'csv',  "output CSV" ],
    [ 'help', "print usage message and exit" ],
);
print($usage->text), exit if $opt->help;

my @args = parse_args(@ARGV) or do {
    print STDERR "At least one set of FastQ files is required\n\n";
    print STDERR $usage->text;
    exit 1;
};

if (grep { $_ < 3 or $_ > 4 } map { scalar @$_ } @args) {
    print STDERR
        "Each stage requires a name, forward reads, and reverse reads.  Orphans are optional.\n",
        "At least one of your stages has too few or too many arguments.\n\n",
        $usage->text;
    exit 1;
}

my @stages = stages_from(@args);
if ($opt->csv) {
    stages_to_csv(@stages);
} else {
    stages_to_text(@stages);
}
